# Generated by Django 5.2.17 on 2026-08-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["full_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
