# Generated by Django 5.2.17 on 2026-08-29 12:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professional", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professional",
            options={
                "ordering": ["user__full_name"],
                "verbose_name": "Professional",
                "verbose_name_plural": "Professionals",
            },
        ),
        migrations.AlterField(
            model_name="professional",
            name="rating_average",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="total_reviews",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
